#!/usr/bin/env bash

docker-compose up -d --build

sleep 5

docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic foo --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic bar --partitions 1 --replication-factor 1


docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic tablea --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic transactions --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic delayed.transactions --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic creditCards --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic stores --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic pending --partitions 1 --replication-factor 1
docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic finance --partitions 1 --replication-factor 1
